### ISSUE TITLE
Can't install: sudo /usr/local/bin/pypi-install pyinsane2 fails

### ISSUE THREAD

**Issue by nodiscc** [openpaperwork/paperwork#578]
Though the problem is with pyinsane/stdeb and not paperwork itself, the installation (following latest doc, https://github.com/jflesch/paperwork/commit/10622efdc30bf967a308674d26081dee92affcfe) fails when running `sudo /usr/local/bin/pypi-install pyinsane2`. All previous installation steps are successful (removed *all* pip2/pip3 and related distribution python packages, `sudo apt-get install python3-all-dev python3-pip; sudo pip3 install stdeb; sudo /usr/local/bin/pypi-install pyocr` 

Quand soudain

```
$ sudo /usr/local/bin/pypi-install pyinsane2
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
running the following command in directory: deb_dist/tmp_py2dsc/pyinsane2-2.0.9
/usr/bin/python3 setup.py --command-packages stdeb.command sdist_dsc --dist-dir=/tmp/tmpi4f1k43q/deb_dist --use-premade-distfile=/tmp/tmpi4f1k43q/pyinsane2-2.0.9.tar.gz bdist_deb
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
no previously-included directories found matching 'doc/.build'

Installed /tmp/tmpi4f1k43q/deb_dist/tmp_py2dsc/pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg
running sdist_dsc
running egg_info
writing top-level names to pyinsane2.egg-info/top_level.txt
writing pyinsane2.egg-info/PKG-INFO
writing dependency_links to pyinsane2.egg-info/dependency_links.txt
writing requirements to pyinsane2.egg-info/requires.txt
reading manifest file 'pyinsane2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.glade' under directory 'src'
warning: no files found matching '*.xml' under directory 'src'
warning: no files found matching '*.css' under directory 'src'
warning: no files found matching 'example-paperwork.conf'
writing manifest file 'pyinsane2.egg-info/SOURCES.txt'
CALLING dpkg-source -b pyinsane2-2.0.9 pyinsane2_2.0.9.orig.tar.gz (in dir /tmp/tmpi4f1k43q/deb_dist)
dpkg-source: info: using options from pyinsane2-2.0.9/debian/source/options: --extend-diff-ignore=\.egg-info$
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building pyinsane2 using existing ./pyinsane2_2.0.9.orig.tar.gz
dpkg-source: info: building pyinsane2 in pyinsane2_2.0.9-1.debian.tar.xz
dpkg-source: info: building pyinsane2 in pyinsane2_2.0.9-1.dsc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: info: source package pyinsane2
dpkg-buildpackage: info: source version 2.0.9-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Jerome Flesch <jflesch@gmail.com>
 dpkg-source --before-build pyinsane2-2.0.9
dpkg-source: info: using options from pyinsane2-2.0.9/debian/source/options: --extend-diff-ignore=\.egg-info$
 fakeroot debian/rules clean
dh clean --with python3 --buildsystem=python_distutils
dh: Compatibility levels before 9 are deprecated (level 7 in use)
   dh_testdir -O--buildsystem=python_distutils
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/tmp/tmpi4f1k43q/deb_dist/pyinsane2-2.0.9'
python3 setup.py clean -a
no previously-included directories found matching 'doc/.build'

Installed /tmp/tmpi4f1k43q/deb_dist/pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg
running clean
'build/lib' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.5' does not exist -- can't clean it
find . -name \*.pyc -exec rm {} \;
make[1]: Leaving directory '/tmp/tmpi4f1k43q/deb_dist/pyinsane2-2.0.9'
   dh_clean -O--buildsystem=python_distutils
dh_clean: Compatibility levels before 9 are deprecated (level 7 in use)
 dpkg-source -b pyinsane2-2.0.9
dpkg-source: info: using options from pyinsane2-2.0.9/debian/source/options: --extend-diff-ignore=\.egg-info$
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building pyinsane2 using existing ./pyinsane2_2.0.9.orig.tar.gz
dpkg-source: warning: file pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/EGG-INFO/SOURCES.txt has no final newline (either original or modified version)
dpkg-source: info: local changes detected, the modified files are:
 pyinsane2-2.0.9/.eggs/README.txt
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/EGG-INFO/PKG-INFO
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/EGG-INFO/SOURCES.txt
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/EGG-INFO/dependency_links.txt
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/EGG-INFO/entry_points.txt
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/EGG-INFO/not-zip-safe
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/EGG-INFO/top_level.txt
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/man/man1/nosetests.1
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/__init__.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/__main__.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/case.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/commands.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/config.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/core.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/exc.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/ext/__init__.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/ext/dtcompat.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/failure.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/importer.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/inspector.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/loader.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/__init__.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/allmodules.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/attrib.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/base.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/builtin.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/capture.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/collect.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/cover.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/debug.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/deprecated.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/doctests.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/errorclass.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/failuredetail.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/isolate.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/logcapture.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/manager.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/multiprocess.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/plugintest.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/prof.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/skip.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/testid.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/plugins/xunit.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/proxy.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/pyversion.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/result.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/selector.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/sphinx/__init__.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/sphinx/pluginopts.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/suite.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/tools/__init__.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/tools/nontrivial.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/tools/trivial.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/twistedtools.py
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/usage.txt
 pyinsane2-2.0.9/.eggs/nose-1.3.7-py3.5.egg/nose/util.py
dpkg-source: info: you can integrate the local changes with dpkg-source --commit
dpkg-source: error: aborting due to unexpected upstream changes, see /tmp/pyinsane2_2.0.9-1.diff.ge6vcU
dpkg-buildpackage: error: dpkg-source -b pyinsane2-2.0.9 gave error exit status 2
Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    setup_requires=['nose>=1.0'],
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/dist-packages/stdeb/command/sdist_dsc.py", line 140, in run
    remove_expanded_source_dir=self.remove_expanded_source_dir,
  File "/usr/local/lib/python3.5/dist-packages/stdeb/util.py", line 1421, in build_dsc
    dpkg_genchanges(cwd=fullpath_repackaged_dirname)
  File "/usr/local/lib/python3.5/dist-packages/stdeb/util.py", line 538, in dpkg_genchanges
    process_command(args,cwd=cwd)
  File "/usr/local/lib/python3.5/dist-packages/stdeb/util.py", line 183, in process_command
    check_call(args, cwd=cwd)
  File "/usr/local/lib/python3.5/dist-packages/stdeb/util.py", line 46, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 2
ERROR running: /usr/bin/python3 setup.py --command-packages stdeb.command sdist_dsc --dist-dir=/tmp/tmpi4f1k43q/deb_dist --use-premade-distfile=/tmp/tmpi4f1k43q/pyinsane2-2.0.9.tar.gz bdist_deb
ERROR in deb_dist/tmp_py2dsc/pyinsane2-2.0.9
Traceback (most recent call last):
  File "/usr/local/bin/pypi-install", line 67, in <module>
    main()
  File "/usr/local/bin/pypi-install", line 53, in main
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'py2dsc-deb pyinsane2-2.0.9.tar.gz' returned non-zero exit status 1
```

My machine runs debian stretch/sid. pip3 installed `stdeb` is at version 0.8.5.

**Comment by jflesch** [comment]
> dpkg-source: info: building pyinsane2 using existing ./pyinsane2_2.0.9.orig.tar.gz

This is weird, it seems to reuse a previous checkout (probably made with pypi-install for Python 2.7 I would guess)

**Comment by jflesch** [comment]
> dpkg-source: error: aborting due to unexpected upstream changes, see /tmp/pyinsane2_2.0.9-1.diff.ge6vcU

Can you have a look at ```/tmp/pyinsane2_2.0.9-1.diff.ge6vcU``` (or whatever the name will be at your next try). I think it would give us a good hint about what's going on here.

**Comment by nodiscc** [comment]
Sorry for the delay. I will investigate as soon as possible.

**Comment by nodiscc** [comment]
as the name indicates the file is a (long) diff, what is weird is it only made of additions, no code deletions: https://gist.github.com/nodiscc/1d89b295b314d02d774739a35d9fae8c

I've tried finding cached versions of pyinsane (using `locate, find`) on my filesystem but found no results. Can this be a bug in stdeb?

**Comment by nodiscc** [comment]
I don't have this problem anymore with the latest version and installation instructions from https://github.com/openpaperwork/paperwork/blob/unstable/doc/install.debian.markdown.

Thanks!

**Comment by jflesch** [comment]
Hm, weird. I haven't released any version of Paperwork since February 9th, so I don't know what has actually solved your issue :/

**Comment by nodiscc** [comment]
This method worked for me as described in the docs:

`sudo aptitude install python3-pip python3-setuptools python3-dev python3-pil libenchant-dev python3-whoosh && sudo pip3 install paperwork && paperwork-shell chkdeps paperwork_backend && paperwork-shell chkdeps paperwork`. I think trying to install through pipy-install is what originally caused the error.

**Comment by pacien** [comment]
No need to give up with `pypi-install` and perform a global install with `pip`.
I could get around this issue by running successively `pypi-install --release 1.3.7 nose` and `pypi-install pyinsane2` again.

I am unsure about the root cause of this problem, but it seems that the required version of nose is `nose>=1.0` whereas nose versions are `['1.3.7', '1.3.6', '1.3.5', '1.3.4', '1.3.3', '1.3.2', '1.3.1', '1.3.0', '1.2.1', '1.2.0', '1.1.2', '1.0.0']`. Perhaps a version numbering problem?
