### ISSUE TITLE
[pw-shell 1.1.2] help should be available for commands

### ISSUE THREAD

**Issue by tYYGH** [openpaperwork/paperwork#591]
```
19:06:51 [yves:~] $ paperwork-shell import --help
usage: paperwork-shell [-h] [-v] [-b] command [arg [arg ...]]

Paperwork shell

positional arguments:
  command     Command. Can be: chkdeps, help, scan, add_label, delete_doc,
              dump, export_all, export_doc, guess_labels, import,
              remove_label, rename, rescan, search, show, switch_workdir
  arg         Command arguments

optional arguments:
  -h, --help  show this help message and exit
  -v          verbose
  -b          non-interactive mode

19:07:36 [yves:~] $ paperwork-shell import
Nothing to import.

19:07:48 [yves:~] $ paperwork-shell import Desktop/13-02-2017-Ordre\ de\ Service.pdf
Traceback (most recent call last):
  File "/usr/bin/paperwork-shell", line 187, in <module>
    sys.exit(COMMANDS[args.cmd](*args.cmd_args))
  File "/usr/lib/python3.6/site-packages/paperwork_backend/shell.py", line 374, in cmd_import
    return _do_import(args, dsearch, doc, guess_labels)
  File "/usr/lib/python3.6/site-packages/paperwork_backend/shell.py", line 303, in _do_import
    fileuri = GLib.filename_to_uri(filepath)
GLib.Error: g_convert_error: The pathname 'Desktop/13-02-2017-Ordre de Service.pdf' is not an absolute path (5)
```
The Paperwork shell is not “discover-able”; it should be.

**Comment by jflesch** [comment]
Try ```paperwork-shell help import```.
But I agree, I must make things clearer

**Comment by jflesch** [comment]
Unfortunately, I'm limited by ```argparse``` :/
The only improvement I've been able to do: https://github.com/openpaperwork/paperwork-backend/commit/31a461a0b7fb801b6cfd688f7ad8917281388e65

**Comment by tYYGH** [comment]
It’s good :-)
