### ISSUE TITLE
[pw-shell 1.1.2] relative paths should work too

### ISSUE THREAD

**Issue by tYYGH** [openpaperwork/paperwork#592]
```
19:07:48 [yves:~] $ paperwork-shell import Desktop/13-02-2017-Ordre\ de\ Service.pdf
Traceback (most recent call last):
  File "/usr/bin/paperwork-shell", line 187, in <module>
    sys.exit(COMMANDS[args.cmd](*args.cmd_args))
  File "/usr/lib/python3.6/site-packages/paperwork_backend/shell.py", line 374, in cmd_import
    return _do_import(args, dsearch, doc, guess_labels)
  File "/usr/lib/python3.6/site-packages/paperwork_backend/shell.py", line 303, in _do_import
    fileuri = GLib.filename_to_uri(filepath)
GLib.Error: g_convert_error: The pathname 'Desktop/13-02-2017-Ordre de Service.pdf' is not an absolute path (5)

19:08:48 [yves:~] 1 $ paperwork-shell import ~/Desktop/13-02-2017-Ordre\ de\ Service.pdf 
/ici/home/yves/Desktop/13-02-2017-Ordre de Service.pdf:
{'Document(s)': 1, 'Image file(s)': 0, 'PDF': 1, 'Page(s)': 4}
```
Relative paths seem to cause an error. This should not happen. Surely this could be solved in Python, else a small shell shim would do the job.

**Comment by jflesch** [comment]
Fixed in 1.2 while switching fully to Gio.
