### ISSUE TITLE
Scanner not found

### ISSUE THREAD

**Issue by schmodd** [openpaperwork/paperwork#632]
- Windows 10 x64
- HP 1610 All in one
- tried running paperwork with admin rights - same problem
- I can scan via Windows without problems but paperwork doesn't recognize the printer/scanner.

LOG (pyinsane2 shows failed to access scanner):
INFO   paperwork.paperwork            System locale: de_DE
INFO   paperwork.paperwork            Glib locale: ['de_DE', 'de', 'C']
INFO   paperwork.paperwork            [Win] Locale path successfully set C:\Program Files\Paperwork\share\locale
INFO   paperwork.paperwork            Using locales in 'C:\Program Files\Paperwork\share\locale'
INFO   paperwork_backend.config       Config file found: C:\Users\user/.config/paperwork.conf
INFO   paperwork_backend.config       Reloading C:\Users\user/.config/paperwork.conf ...
INFO   paperwork.frontend.util        UI file used: C:\Program Files\Paperwork\data\mainwindow\appmenu.xml
INFO   paperwork.frontend.util        CSS file used: C:\Program Files\Paperwork\data\application.css
INFO   paperwork.frontend.util        UI file used: C:\Program Files\Paperwork\data\mainwindow\mainwindow.glade
INFO   paperwork.frontend.util.jobs   [Scheduler Index search / update] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Index search / update] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Scan] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Scan] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Page boxes loader] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Page boxes loader] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Progress] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Progress] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Export] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Export] Started
INFO   paperwork.frontend.util.jobs   [Scheduler OCR] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler OCR] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Main] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Main] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Search] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Search] Started
INFO   paperwork.frontend.util.actions Action: [Refresh index]
INFO   paperwork_backend.docsearch    Opening index dir 'C:\Users\user/.local\share\paperwork\index' ...
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.mainwindow  Image view port resized. (0, 0) --> (714, 710)
INFO   paperwork.frontend.mainwindow  Changing zoom level (internal): True/1.0
INFO   paperwork.frontend.mainwindow  Image view port resized. (714, 710) --> (714, 707)
INFO   paperwork.frontend.mainwindow  Changing zoom level (internal): True/1.0
INFO   paperwork.frontend.util.actions Action: [Set document date]
INFO   paperwork.frontend.mainwindow.docs Invalid date: New document
INFO   paperwork.frontend.mainwindow  Document examen finished. Updating index ...
INFO   paperwork.frontend.mainwindow  3 labels found
INFO   paperwork.frontend.mainwindow  New document: 0
INFO   paperwork.frontend.mainwindow  Updated document: 0
INFO   paperwork.frontend.mainwindow  Deleted document: 0
INFO   paperwork.frontend.mainwindow  No changes
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.mainwindow  Searching: []
INFO   paperwork.frontend.mainwindow  Got 48 documents
INFO   paperwork.frontend.mainwindow.docs Will display documents 0:50 (actual number: 48)
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.mainwindow  Got 0 suggestions
INFO   paperwork.frontend.mainwindow.docs Will get thumbnails for 7 documents [0-7]
INFO   paperwork.frontend.mainwindow.docs Start thumbnailing 7 documents (DocThumbnailer:0)
INFO   paperwork.frontend.mainwindow.docs [DocThumbnailer:0]: Got thumbnail for 20170219_0810_21 (0.002003s)
INFO   paperwork.frontend.mainwindow.docs [DocThumbnailer:0]: Got thumbnail for 20161207_1845_10 (0.003003s)
INFO   paperwork.frontend.mainwindow.docs [DocThumbnailer:0]: Got thumbnail for 20161111_2148_43 (0.002002s)
INFO   paperwork.frontend.mainwindow.docs [DocThumbnailer:0]: Got thumbnail for 20161023_0747_12 (0.003003s)
INFO   paperwork.frontend.mainwindow.docs [DocThumbnailer:0]: Got thumbnail for 20161007_1549_18 (0.003004s)
INFO   paperwork.frontend.mainwindow.docs [DocThumbnailer:0]: Got thumbnail for 20160911_0931_04 (0.002002s)
INFO   paperwork.frontend.mainwindow.docs [DocThumbnailer:0]: Got thumbnail for 20160911_0930_08 (0.003005s)
INFO   paperwork.frontend.mainwindow.docs End of thumbnailing [DocThumbnailer:0]
INFO   paperwork.frontend.util.actions Action: [Opening diagnostic dialog]
INFO   paperwork.frontend.util        UI file used: C:\Program Files\Paperwork\data\diag\diagdialog.glade
INFO   paperwork.frontend.diag        ====== START OF SYSTEM INFO ======
INFO   paperwork.frontend.diag        os.name: nt
INFO   paperwork.frontend.diag        sys.version: 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]
INFO   paperwork.frontend.diag        platform.architecture: ('64bit', 'WindowsPE')
INFO   paperwork.frontend.diag        platform.platform: Windows-10-10.0.15063-SP0
INFO   paperwork.frontend.diag        platform.processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
INFO   paperwork.frontend.diag        platform.version: 10.0.15063
INFO   paperwork.frontend.diag        platform.linux_distribution: ('', '', '')
INFO   paperwork.frontend.diag        platform.win32_ver: ('10', '10.0.15063', 'SP0', 'Multiprocessor Free')
INFO   paperwork.frontend.diag        multiprocessing.cpu_count: 4
ERROR  paperwork.frontend.diag        'module' object has no attribute 'sysconf'
Traceback (most recent call last):
  File "site-packages\paperwork-1.1.2-py3.4.egg\paperwork\frontend\diag\__init__.py", line 78, in _get_sysinfo
AttributeError: 'module' object has no attribute 'sysconf'
INFO   paperwork.frontend.diag        ====== END OF SYSTEM INFO ======
INFO   paperwork.frontend.diag        ====== START OF PAPERWORK INFO ======
INFO   paperwork.frontend.diag        Paperwork version: 1.1.2
INFO   paperwork.frontend.diag        Total number of documents: 48
INFO   paperwork.frontend.diag        Document types: {"<class 'paperwork_backend.img.doc.ImgDoc'>": 24, "<class 'paperwork_backend.pdf.doc.PdfDoc'>": 22}
INFO   paperwork.frontend.diag        Total number of pages: 208 (average: 4.333333333333333/doc)
INFO   paperwork.frontend.diag        Maximum number of pages in one document: 30
INFO   paperwork.frontend.diag        Total number of words: 97654 (average: 469.49038461538464/page)
INFO   paperwork.frontend.diag        Average word length: 6.525150019456448
INFO   paperwork.frontend.diag        Max word length: 192
INFO   paperwork.frontend.diag        ====== END OF PAPERWORK INFO ======
INFO   paperwork.frontend.diag        ====== START OF SCANNER INFO ======
WARNING pyinsane2.wia.abstract         Failed to access scanner ('{6BDD1FC6-810F-11D0-BEC7-08002BE2092F}\\0000', 'HP psc 1600 series') : WIA: Failed to get scanner properties
ERROR  pyinsane2.wia.abstract         WIA: Failed to get scanner properties
Traceback (most recent call last):
  File "site-packages\pyinsane2-2.0.9-py3.4-win-amd64.egg\pyinsane2\wia\abstract.py", line 567, in get_devices
  File "site-packages\pyinsane2-2.0.9-py3.4-win-amd64.egg\pyinsane2\wia\abstract.py", line 420, in __init__
  File "site-packages\pyinsane2-2.0.9-py3.4-win-amd64.egg\pyinsane2\wia\abstract.py", line 470, in reload_options
  File "site-packages\pyinsane2-2.0.9-py3.4-win-amd64.egg\pyinsane2\wia\rawapi.py", line 111, in get_properties
  File "site-packages\pyinsane2-2.0.9-py3.4-win-amd64.egg\pyinsane2\wia\rawapi.py", line 33, in wait
  File "site-packages\pyinsane2-2.0.9-py3.4-win-amd64.egg\pyinsane2\wia\rawapi.py", line 38, in do
  File "site-packages\pyinsane2-2.0.9-py3.4-win-amd64.egg\pyinsane2\wia\rawapi.py", line 106, in _get_properties
pyinsane2.wia.rawapi.WIAException: WIA: Failed to get scanner properties
INFO   paperwork.frontend.diag        0 scanners found
INFO   paperwork.frontend.diag        ====== END OF SCANNER INFORMATIONS ======

**Comment by jflesch** [comment]
That's weird, this error usually happens when the scanner is turned off / offline

**Comment by schmodd** [comment]
I am still having the same problem with the new paperwork version 1.21 (by the way #590 describes it too)
My Printer & paperwork are working fine under linux (with sane) but not in windows (with wia).
I want to mention that my Scanner works without any problem with the "windows-scanner"-app and also the "Windows-Fax and Scan"-tool though. That leads me to the conclusion that there may be something wrong with the pyinsane implementation.
