### ISSUE TITLE
Scan failed after multi-scan

### ISSUE THREAD

**Issue by Pafzedog** [openpaperwork/paperwork#633]
After scanning several documents by feeder , I got "scan failed : no paper found" (scan échoué : pas de papier trouvé) when I want to scan a  new document.
I have to quit and launch  "paperwork" to get the scanner  work again. 
[paperwork_diag.txt](https://github.com/openpaperwork/paperwork/files/981126/paperwork_diag.txt)

**Comment by jflesch** [comment]
```
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/actions.py", line 67, in on_button_clicked_cb
    return self.__do()
  File "/usr/local/lib/python3.5/dist-packages/paperwork/frontend/util/actions.py", line 64, in __do
    return self.do(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 1404, in do
    scan_session = dev.scan(multiple=False)
  File "/usr/local/lib/python3.5/dist-packages/pyinsane2/sane/abstract_proc.py", line 258, in scan
    return ScanSession(self, multiple)
  File "/usr/local/lib/python3.5/dist-packages/pyinsane2/sane/abstract_proc.py", line 198, in __init__
    self._remote_session = remote_do('scan', scanner.name, multiple)
  File "/usr/local/lib/python3.5/dist-packages/pyinsane2/sane/abstract_proc.py", line 74, in remote_do
    raise exc_class(*result['exception_args'])
StopIteration
```

That's weird. In Pyinsane, StopIteration == no more paper in the feeder.
I have a Brother MFC so I will have a look. Maybe a regression.

**Comment by yastupin** [comment]
Same bug encountered here. What can I do to help?
Scanner Brother ADS-1600W, Paperwork 1.1.2 on Fedora 25.

```
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/paperwork/frontend/util/actions.py", line 67, in on_button_clicked_cb
    return self.__do()
  File "/usr/lib/python3.5/site-packages/paperwork/frontend/util/actions.py", line 64, in __do
    return self.do(**kwargs)
  File "/usr/lib/python3.5/site-packages/paperwork/frontend/multiscan/__init__.py", line 184, in do
    scan_session = dev.scan(multiple=True)
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 258, in scan
    return ScanSession(self, multiple)
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 198, in __init__
    self._remote_session = remote_do('scan', scanner.name, multiple)
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 74, in remote_do
    raise exc_class(*result['exception_args'])
StopIteration
ERROR  paperwork.frontend.diag        ===========================
```

Works again after a restart.

**Comment by jflesch** [comment]
Not much you can do. I have a Brother scanner at home. I'm fairly certain I will be able to reproduce this issue. The only problem now is that I lack free time ... (I'm in the process of moving to another region of France)

**Comment by jflesch** [comment]
While I have time to make a new release, I don't think I will have time to look at this issue before ~1 month (I can work on Paperwork during my lunch break at work, but my scanner is at home, and I'm currently busy packaging all my stuff).

Therefore, I'll fix it only later, for 1.2.1, sorry.

**Comment by Pafzedog** [comment]
no problems :)
Thanks for the feedback

**Comment by jflesch** [comment]
Reproduced here with Ubuntu Gnome 17.04 + Brother MFC-7360N.

Interestingly, it only happens if the exact number of pages specified by the user has been scanned. In other words, if you specify more pages than what must be scanned (for instance 99 pages for actually a 2-pages documents), the bug doesn't occur.

**Comment by jflesch** [comment]
5a3d787f80d288d566f9d5452a7e2e0f1da56388
