### ISSUE TITLE
Crash: Unable to recognize the image format of paperwork_halo.svg

### ISSUE THREAD

**Issue by mermetbt** [openpaperwork/paperwork#634]
Hi,
I've just installed Paperwork from the AUR repository on Archlinux.
The application didn't start, and I get the following trace:

```
(paperwork:26335): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(paperwork:26335): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(paperwork:26335): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
INFO   paperwork.paperwork            Using locales in '/usr/share/locale'
INFO   pyinsane2.sane.abstract_proc   Starting Pyinsane subprocess
INFO   pyinsane2.sane.abstract_proc   Pyinsane pipes: /tmp/pyinsane_a3rnx0yq/pipe_c2s | /tmp/pyinsane_a3rnx0yq/pipe_s2c
INFO   pyinsane2.sane.abstract_proc   Connected to Pyinsane subprocess
INFO   paperwork_backend.config       Config file not found. Will use '/home/tmermetbuffet/.config/paperwork.conf'
INFO   paperwork_backend.config       Reloading /home/tmermetbuffet/.config/paperwork.conf ...
/usr/lib/python3.6/site-packages/paperwork/frontend/mainwindow/__init__.py:2779: Warning: g_set_application_name() called multiple times
  GLib.set_application_name(_("Paperwork"))
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/mainwindow/appmenu.xml
INFO   paperwork.frontend.util        CSS file used: /usr/share/paperwork/application.css
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/mainwindow/mainwindow.glade

(paperwork:26335): Gtk-WARNING **: Could not load image 'paperwork': Impossible d'ouvrir le fichier « /usr/share/paperwork/mainwindow/paperwork » : Aucun fichier ou dossier de ce type
INFO   paperwork.paperwork            Good bye
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/usr/bin/paperwork", line 6, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/paperwork/paperwork.py", line 144, in main
    main_win = MainWindow(config)
  File "/usr/lib/python3.6/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2311, in __init__
    self.window = self.__init_window(widget_tree, config)
  File "/usr/lib/python3.6/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2849, in __init_window
    logo = GdkPixbuf.Pixbuf.new_from_file(logo_path)
GLib.GError: gdk-pixbuf-error-quark: Impossible de reconnaître le format d'image du fichier « /usr/share/icons/hicolor/scalable/apps/paperwork_halo.svg » (3)
ERROR  paperwork.frontend.diag        ===========================
```

```
python --version
Python 3.6.1
```

Regards,

**Comment by jflesch** [comment]
Looks like Gdk was compiled without SVG support. This is a ticket for the AUR maintainer, not upstream.

**Comment by mermetbt** [comment]
I found the solution. The problem was that I used the infinality font package.
So in order to fix the problem I did the following:

1. Remove the fontconfig infinality package
pacman -R fontconfig-infinality

2. Remove infinality:
pacman -S --asdeps fontconfig cairo freetype2

3. Update the GDK Pixbuf loader:
gdk-pixbuf-query-loaders --update-cache

And then everything works fine!
