### ISSUE TITLE
[DnD] Exception when drag'n'droping the last page of a document into another

### ISSUE THREAD

**Issue by jflesch** [openpaperwork/paperwork#669]
When drag'n'droping the last page of document into another:

Expecting behavior:
- The target document gets the page appended
- The origin document is deleted

Result:
- The target document gets the page appended
- Exception

**Comment by jflesch** [comment]
[diag.txt](https://github.com/openpaperwork/paperwork/files/1253761/diag.txt)

**Comment by jflesch** [comment]
Happens on Linux too:

```
INFO   paperwork.frontend.mainwindow.pages Drag-n-drop begin: selected: [20170918_2147_59|0]
INFO   paperwork.frontend.mainwindow.pages Drag-n-drop get: selected: [20170918_2147_59|0]
INFO   paperwork.frontend.mainwindow.docs Drag-n-drop data received on doc list: [20170918_2147_59|0] --> [20170918_2138_51]
INFO   paperwork_backend.img.doc      Adding page 2 to 20170918_2138_51 (file:///home/jflesch/SparkleShare/papers/20170918_2138_51)
INFO   paperwork_backend.img.page     Destroying page: 20170918_2147_59 p1
INFO   paperwork_backend.common.doc   Destroying doc: file:///home/jflesch/SparkleShare/papers/20170918_2147_59
INFO   paperwork_backend.fs           Deleting file:///home/jflesch/SparkleShare/papers/20170918_2147_59 ...
INFO   paperwork_backend.common.doc   Done
INFO   paperwork_backend.common.doc   Destroying doc: file:///home/jflesch/SparkleShare/papers/20170918_2147_59
INFO   paperwork_backend.fs           Deleting file:///home/jflesch/SparkleShare/papers/20170918_2147_59 ...
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paperwork_backend-1.2.1-py3.5.egg/paperwork_backend/fs.py", line 326, in rm_rf
    if not f.trash():
GLib.GError: g-io-error-quark: Erreur lors de la mise à la corbeille du fichier /home/jflesch/SparkleShare/papers/20170918_2147_59 : Aucun fichier ou dossier de ce type (1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.2.1-py3.5.egg/paperwork/frontend/mainwindow/docs.py", line 892, in _on_drag_data_received
    src_page.doc.destroy()
  File "/usr/local/lib/python3.5/dist-packages/paperwork_backend-1.2.1-py3.5.egg/paperwork_backend/common/doc.py", line 122, in destroy
    self.fs.rm_rf(self.path)
  File "/usr/local/lib/python3.5/dist-packages/paperwork_backend-1.2.1-py3.5.egg/paperwork_backend/fs.py", line 329, in rm_rf
    raise IOError(str(exc))
OSError: g-io-error-quark: Erreur lors de la mise à la corbeille du fichier /home/jflesch/SparkleShare/papers/20170918_2147_59 : Aucun fichier ou dossier de ce type (1)
ERROR  paperwork.frontend.diag        ===========================
```

**Comment by jflesch** [comment]
f476453e0869371d6e1e905d4bbcadc5ee2b422d
