### ISSUE TITLE
[Flatpak] Printing doesn't work

### ISSUE THREAD

**Issue by jflesch** [openpaperwork/paperwork#716]
Branch: develop (not tested yet on master)
Can't open the printing dialog.

```
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/paperwork-1.3-py3.5.egg/paperwork/frontend/util/actions.py", line 97, in on_action_activated_cb
    return self.__do()
  File "/app/lib/python3.5/site-packages/paperwork-1.3-py3.5.egg/paperwork/frontend/util/actions.py", line 64, in __do
    return self.do(**kwargs)
  File "/app/lib/python3.5/site-packages/paperwork-1.3-py3.5.egg/paperwork/frontend/mainwindow/__init__.py", line 1353, in do
    self.__main_win.window)
GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files (2)
ERROR  paperwork.frontend.diag        ===========================
```

**Comment by jflesch** [comment]
[diag.txt](https://github.com/openpaperwork/paperwork/files/1527497/diag.txt)

**Comment by jflesch** [comment]
Maybe related to my use of Awesome instead of Gnome.

**Comment by jflesch** [comment]
confirmed: it was specific to my setup
