### ISSUE TITLE
Newly imported documents only available after restart

### ISSUE THREAD

**Issue by Moini** [openpaperwork/paperwork#721]
After importing multiple pdfs from a nested directory tree (into a new installation), and the animation stopping, no new documents seem to be available. A search via search bar turns up no results (searched for my name, which should have been there somewhere).

After closing and reopening the application, the documents are available.

This is with paperwork 1.2.2 (flatpak) on Linux Mint 18.3.

**Comment by jflesch** [comment]
Hm, can you:
1) do an import
2) get the [diagnostic output](https://openpaper.work/helpdesk/kb/1/) and post it here please ?

Based on your description, I would assume that some sort of error/exception occured while examing your PDFs.

**Comment by Moini** [comment]
How can I reset the full flatpak installation? Just delete the folder in my home directory?

**Comment by Moini** [comment]
Scan > Import file(s) > select folder > import all pdfs in folder as separate documents > get desktop notification "Imported: 194 pdfs" etc. > wait until animation / computer's fan activity finishes.

Now, I wish I could get diagnostics, after spending so much time waiting for the import to run, but that dialog doesn't react to clicks. I can neither copy nor save nor scroll nor close the dialog without getting a message that the program doesn't react and would I like to close the application... clicked on Save as... first :-(

I had that dialog opened previously and had been able to scroll. But then I hadn't clicked on Save. Not sure if that could be causing it :-/

**Comment by Moini** [comment]
Would it also print that info to the terminal?

**Comment by jflesch** [comment]
Yes it does

**Comment by Moini** [comment]
Merci!

[paperworks.txt](https://github.com/openpaperwork/paperwork/files/1564946/paperworks.txt)

I've obfuscated the file names, sorry. If you need to know the relation between specific files, please let me know the lines. I've kept the original output.

**Comment by Moini** [comment]
One issue with flatpak is that, by default, it only seems to be allowed to access one's home directory.   My files are on another drive, and I had to use 

`flatpak override --user --filesystem=/media/disk1/username/document_directory/ work.openpaper.Paperwork`

Maybe access to more directories is required?

**Comment by jflesch** [comment]
Ah, then that is clearly the problem yes. Flatpak containers have a reduced access to the file system, and yes, Paperwork's container is limited to /home. I'll add that information to the documentation.

**Comment by jflesch** [comment]
Ok got it:
```
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/paperwork-1.2.2-py3.5.egg/paperwork/frontend/mainwindow/__init__.py", line 3772, in _show_doc_hook
    self._show_doc_internal(doc, force_refresh)
  File "/app/lib/python3.5/site-packages/paperwork-1.2.2-py3.5.egg/paperwork/frontend/mainwindow/__init__.py", line 3757, in _show_doc_internal
    self._show_pages(doc)
  File "/app/lib/python3.5/site-packages/paperwork-1.2.2-py3.5.egg/paperwork/frontend/mainwindow/__init__.py", line 3709, in _show_pages
    first_scan_drawer = self.__reset_page_drawers(doc)
  File "/app/lib/python3.5/site-packages/paperwork-1.2.2-py3.5.egg/paperwork/frontend/mainwindow/__init__.py", line 3625, in __reset_page_drawers
    sentence=search)
  File "/app/lib/python3.5/site-packages/paperwork-1.2.2-py3.5.egg/paperwork/frontend/mainwindow/pages.py", line 1217, in __init__
    self, page.size, job_factories, job_schedulers, sentence,
  File "/app/lib/python3.5/site-packages/paperwork_backend-1.2.2-py3.5.egg/paperwork_backend/pdf/page.py", line 237, in size
  File "/app/lib/python3.5/site-packages/paperwork_backend-1.2.2-py3.5.egg/paperwork_backend/pdf/page.py", line 259, in get_size
  File "/app/lib/python3.5/site-packages/paperwork_backend-1.2.2-py3.5.egg/paperwork_backend/pdf/page.py", line 252, in get_base_size
  File "/app/lib/python3.5/site-packages/paperwork_backend-1.2.2-py3.5.egg/paperwork_backend/pdf/page.py", line 100, in pdf_page
  File "/app/lib/python3.5/site-packages/paperwork_backend-1.2.2-py3.5.egg/paperwork_backend/pdf/doc.py", line 131, in get_pdf
GLib.GError: g-file-error-quark: Too many open files (14)
ERROR  paperwork.frontend.diag        ===========================
```

You're importing a lot of PDF at the same time, and it seems there is a file descriptor leak in the import process

**Comment by jflesch** [comment]
Fix: https://github.com/openpaperwork/paperwork-backend/commit/072fd7ccf3c38c37c3025bebc2819aede48065d9
Will be in the Flatpak repository by tomorrow evening (GMT+1).

**Comment by Moini** [comment]
Thank you! I've now installed it the way it's indicated here:
https://github.com/openpaperwork/paperwork/blob/master/flatpak/README.markdown

Unfortunately, now it gets stuck on a different error. Will open a new report.
