### ISSUE TITLE
Unable to get languages

### ISSUE THREAD

**Issue by RidaAyed** [openpaperwork/paperwork#751]
Hi

Executing
```
$ sudo paperwork-shell chkdeps paperwork
```
I get this message
```
[WARN] Unknown distribution. Can't suggest packages to install
{
    "args": "(1, 'unable to get languages')",
    "exception": "<class 'pyocr.error.TesseractError'>",
    "reason": "(1, 'unable to get languages')",
    "status": "error"
}
Traceback (most recent call last):
  File "/usr/bin/paperwork-shell", line 11, in <module>
    load_entry_point('paperwork-backend==1.2.3', 'console_scripts', 'paperwork-shell')()
  File "/usr/lib/python3.6/site-packages/paperwork_backend/shell_cmd.py", line 214, in main
    sys.exit(COMMANDS[args.cmd](*args.cmd_args))
  File "/usr/lib/python3.6/site-packages/paperwork_backend/shell_cmd.py", line 141, in chkdeps
    _chkdeps(module_name, distribution)
  File "/usr/lib/python3.6/site-packages/paperwork_backend/shell_cmd.py", line 82, in _chkdeps
    missing = module.find_missing_dependencies()
  File "/usr/lib/python3.6/site-packages/paperwork/deps.py", line 310, in find_missing_dependencies
    missing += find_missing_ocr(lang)
  File "/usr/lib/python3.6/site-packages/paperwork/deps.py", line 149, in find_missing_ocr
    langs = ocr_tools[0].get_available_languages()
  File "/usr/lib/python3.6/site-packages/pyocr/tesseract.py", line 406, in get_available_languages
    raise TesseractError(ret, "unable to get languages")
pyocr.error.TesseractError: (1, 'unable to get languages')
```
---
Running
```
$ paperwork
```
I get this message
```
** (paperwork:4192): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
INFO   paperwork.paperwork            Using locales in '/usr/lib/python3.6/site-packages/paperwork/frontend/locale'
INFO   paperwork.paperwork            Initializing pyinsane ...
INFO   pyinsane2.sane.abstract_proc   Starting Pyinsane subprocess
INFO   pyinsane2.sane.abstract_proc   Pyinsane pipes: /tmp/pyinsane_lss3m4n2/pipe_c2s | /tmp/pyinsane_lss3m4n2/pipe_s2c
INFO   pyinsane2.sane.abstract_proc   Connected to Pyinsane subprocess
INFO   paperwork.paperwork            Initializing libnotify ...
INFO   paperwork_backend.config       Config file not found. Will use '/home/ra/.config/paperwork.conf'
INFO   paperwork_backend.config       Reloading /home/ra/.config/paperwork.conf ...
INFO   paperwork.paperwork            Stopping Pyinsane ...
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/usr/bin/paperwork", line 11, in <module>
    load_entry_point('paperwork==1.2.3', 'gui_scripts', 'paperwork')()
  File "/usr/lib/python3.6/site-packages/paperwork/paperwork.py", line 189, in main
    m.main(hook_func, skip_workdir_scan)
  File "/usr/lib/python3.6/site-packages/paperwork/paperwork.py", line 165, in main
    self.config.read()
  File "/usr/lib/python3.6/site-packages/paperwork_backend/config.py", line 188, in read
    setting.load(self._configparser)
  File "/usr/lib/python3.6/site-packages/paperwork_backend/config.py", line 63, in load
    self.value = self.default_value_func()
  File "/usr/lib/python3.6/site-packages/paperwork_backend/config.py", line 115, in get_default_ocr_lang
    ocr_langs = ocr_tools[0].get_available_languages()
  File "/usr/lib/python3.6/site-packages/pyocr/tesseract.py", line 406, in get_available_languages
    raise TesseractError(ret, "unable to get languages")
pyocr.error.TesseractError: (1, 'unable to get languages')
ERROR  paperwork.frontend.diag        ===========================

```
Following the instructions in installation script I installed this package
```
$ tesseract-data-deu
```
Seems fine by my view
`[2018-02-15 08:27] [ALPM] installed tesseract-data-deu (1:3.04.00-1)`

Any ideas what I've missed?

**Comment by jflesch** [comment]
1) What distribution do you use ?
2) Have you installed tesseract ? (and not just the data language file)
3) What does `tesseract --list-langs` says ?

Still, `paperwork-shell chkdeps` shouldn't crash. I'm going to have a look.

**Comment by jflesch** [comment]
Workaround for `paperwork-shell chkdeps` : 104947f21782b2983c9b3b75f5d950355bfcd6cb (still not sure how it could have happened)

**Comment by RidaAyed** [comment]
Solved. After installing (although not needed in my workflow) the package `$ tesseract-data-eng` paperwork works :+1: 

@jflesch Thank you for your lightning fast engagement

**Comment by jflesch** [comment]
Please note that it means there is a missing dependency in your Linux distribution: Tesseract depends on the english training files (don't ask me why). If you have time, you should open a ticket on the bug tracker of your distribution.
